### ISSUE TITLE
Apply wasm-strip to all WASMs

### ISSUE THREAD

**Issue by rauljordan** [OffchainLabs/cargo-stylus#1]
Although we already have `strip = true` in release builds for the Stylus hello world template repository, the cargo stylus tool admits WASMs through file paths directly. We should apply `wasm-strip` to shave off binary sizes if possible. Opening this issue for tracking

**Comment by joshuacolvin0** [comment]
Turns out that `wasm-strip` doesn't reduce size much, so not worth adding extra dependency
