### ISSUE TITLE
The default version of cargo-stylus-base docker image pulled by cargo stylus deploy does not exist on docker.io

### ISSUE THREAD

**Issue by zengatsu** [OffchainLabs/cargo-stylus#106]
Running:
```
cargo stylus deploy \
  --endpoint='http://localhost:8547' \
  --private-key="0xb6b15c8cb491557369f3c7d2c287b053eb229daa9c22138887752191c9520659"
```
  
  Gives the error:
`ERROR: failed to solve: offchainlabs/cargo-stylus-base:0.5.5: docker.io/offchainlabs/cargo-stylus-base:0.5.5: not found`

Because the default version chosen is 0.5.5 which doesn't exist "yet" on [docker.io](https://hub.docker.com/r/offchainlabs/cargo-stylus-base/tags)

The workaround is to to set it manually using option **`--cargo-stylus-version`**
```
cargo stylus deploy 
  --cargo-stylus-version=0.5.3 \
  --endpoint='http://localhost:8547' \
  --private-key="0xb6b15c8cb491557369f3c7d2c287b053eb229daa9c22138887752191c9520659"
```

**Comment by joshuacolvin0** [comment]
Thanks for the report, this has been resolved.

**Comment by VGabriel45** [comment]
Thank you !
