### ISSUE TITLE
`cargo stylus check` with `--wasm-file-path` fails if project is not built

### ISSUE THREAD

**Issue by akirillo** [OffchainLabs/cargo-stylus#20]
Hi there!

I love the Stylus CLI, and I particularly like how `cargo stylus check` will appropriately build your code for the `wasm32-unknown-unknown` target, and check if it is Stylus-valid WASM, all in one.

However, if you add the `--wasm-file-path <PATH>` flag, and the project is not yet built, the command will fail with a:

```
failed to get compressed WASM bytes: could not read WASM file at target path <PATH>: No such file or directory (os error 2)
```

Presumably because the existence of a file at the provided path is checked before the project is built.

**Comment by tsahee** [comment]
that's the expected behavior. wasm-file-path can be used by non-rust programing languages to test/deploy their already-built wasm.
