### ISSUE TITLE
Cargo-Stylus failed to build on Windows

### ISSUE THREAD

**Issue by crypdoughdoteth** [OffchainLabs/cargo-stylus#22]
Hey, yesterday I was trying to install the cargo-stylus cli on Windows; however, I came across a couple errors related to name spaces in the replay module preventing compilation. Below is a screenshot of the error. 

![image](https://github.com/OffchainLabs/cargo-stylus/assets/106392730/8cb335a6-2c1c-4b77-a742-7e304c64e3f8)

**Comment by NotWrench** [comment]
I've received the same error while trying to install

Windows version:
![image](https://github.com/OffchainLabs/cargo-stylus/assets/70622477/8c4bc6ee-82d1-4690-976b-e72055212cc1)

Please check this out!

**Comment by romdotdog** [comment]
Relevant: #18

**Comment by sarvesh1327** [comment]
I am also getting the same error with windows 11. Please let me know if there is a way to resolve this
