### ISSUE TITLE
Testing support

### ISSUE THREAD

**Issue by gregdhill** [OffchainLabs/cargo-stylus#7]
I'm following the quickstart guide [here](https://docs.arbitrum.io/stylus/stylus-quickstart) but it doesn't yet seem possible to run tests. I wanted to modify the `Counter` example with some unit tests and run `cargo test` but that results in a compilation error. Do you plan to support this via another sub-command like `cargo stylus test`?

**Comment by rauljordan** [comment]
hi @gregdhill normal Rust unit tests can be run with `cargo test --features=export-abi --target=aarch64-apple-darwin` or whatever your target architecture is. You can figure this out with `rustc -vV`. We're discussing how to make this easier over time
