### ISSUE TITLE
Create GitHub Project to Improve Coordination and Development

### ISSUE THREAD

**Issue by emnul** [OffchainLabs/cargo-stylus#87]
GitHub projects improve transparency, coordination and release speed. They help contributors quickly understand the project's goals and what they can do to help reach those goals ie improve testing, documentation, add feature, improve performance, etc.

**Comment by joshuacolvin0** [comment]
Spam

**Comment by emnul** [comment]
Hey @joshuacolvin0 the issue raised is genuine. As a contributor outside of the Offchain labs org it's difficult to coordinate without transparent goals and objectives.

**Comment by emnul** [comment]
@rauljordan could this issue be reopened? Taking advantage of the GitHub Project feature would benefit both contributors and maintainers. It would also provide the community more transparency.
