### ISSUE TITLE
stylus verify doesn't work as expected

### ISSUE THREAD

**Issue by xpanvictor** [OffchainLabs/cargo-stylus#99]
The cargo-stylus verification doesn't work with contracts. I get a successful response with the tool but on checking the
sepolia arbiscan, the contract remains unverified.

**Comment by TucksonDev** [comment]
Hey,
`cargo stylus verify` is meant to verify that the code that you have locally matches the on-chain bytecode of a specific address, but it doesn't interact with Arbiscan (or any other block explorer), it's a different process.

To verify the source code of your contract on Arbiscan, you can follow this guide: https://docs.arbitrum.io/stylus/how-tos/verifying-contracts-arbiscan
